2.0 preview
PolymerElements/marked-element pull request #49
Opened 2017-03-01 01:28 UTC by e111077

DO NOT MERGE

Major change:
* `class="marked-element"` no longer works must now use `slot="markdown-html"`

2017-03-27 14:56 UTC, stramel commented on marked-element.html
>          display: none !important;
Can probably remove the IE10 polyfill here?

2017-03-27 15:47 UTC, notwaldorf commented on marked-element.html
>          display: none !important;
It can be replaced with a `hidden` attribute, but the style will still have to stick around since any `display` style on :host will override it

2017-03-31 21:24 UTC, stramel commented on marked-element.html
>          display: none !important;
Sorry, I must be missing something. How would setting a display style on :host override it?

2017-03-31 22:06 UTC, e111077 commented
@notwaldorf breaking change, but do you think we should also remove the selector on the `<slot>`? Was there a need for a selector in the first place?

2017-04-10 18:26 UTC, notwaldorf reviewed
You also need to update the docs at the top of the element

2017-04-10 18:26 UTC, notwaldorf commented on marked-element.html
> +    <slot name="markdown-html"></slot>
Docs need to be updated too

2017-04-10 18:26 UTC, notwaldorf commented on marked-element.html
>          display: none !important;
I meant that 'host` has a `display:block` style, which has higher precedence than the user agent stylesheet `'hidden`. As a result, if you don't provide a style for `:host('hidden')`, then `<marked-element hidden>` won't actually hide the element.

This `hidden` however doesn't apply to the host, but to the `.content` div -- a similar argument can be made there, only I don't think anything sets the `display` of that element to anything else. In any case, doesn't hurt to have it

2017-04-10 18:27 UTC, notwaldorf requested changes
Docs need updating

2017-04-11 00:10 UTC, e111077 commented
@notwaldorf readme readable

2017-04-11 18:45 UTC, notwaldorf approved these changes
🎉

2017-04-18 04:10 UTC, stramel commented
So are we going to keep the named slot? Seems like it would make the public api simpler by doing default slot.

2017-05-12 21:55 UTC, merged