[Feature] `src` support on `script`
PolymerElements/marked-element pull request #51
Opened 2017-03-31 21:07 UTC by stramel

Initial attempt at adding `src` support to the `script[type="text/markdown"]` tag.

Test seems a little shotty.

PTAL and let me know any comments you may have. 😄

2017-04-11 01:40 UTC, stramel commented
@FredKSchott I know you are busy, just a friendly ping :smile:

2017-04-11 19:14 UTC, FredKSchott commented
Completely missed this in my inbox overload last week, thanks for the ping. Reviewing now...

2017-04-11 19:18 UTC, FredKSchott reviewed
🎉 💯  @stramel thanks for tackling this, Overall looks like a good direction design wise. Left a few comments.

2017-04-11 19:18 UTC, FredKSchott commented on README.md
> +via the `markdown` attribute
For each of these different ways to specify source, turn this into a `###` (cleaning up the wording to be more header-like might be needed as well)

2017-04-11 19:18 UTC, FredKSchott commented on demo/example.md
> +[![Build status](https://travis-ci.org/PolymerElements/marked-element.svg?branch=master)](https://travis-ci.org/PolymerElements/marked-element)
is this to test images? Use of the build status is confusing here, consider using a different image.

2017-04-11 19:18 UTC, FredKSchott commented on marked-element.html
> +       * network request.
Only set this if a remote request is needed

2017-04-11 19:18 UTC, FredKSchott commented on marked-element.html
> +      if (this.markdown) return;
Formatting: please expand this and others below:
```
if (this.markdown) {
  return;
}
```

2017-04-11 19:18 UTC, FredKSchott commented on marked-element.html
> +      var markdownElement = Polymer.dom(this).querySelector('[type^="text/markdown"]');
Are there any values other than "text/markdown" that start with "text/markdown"? If so, can you give an example in the comment above?

2017-04-11 19:18 UTC, FredKSchott commented on marked-element.html
> +        this.markdown = this._unindent(markdownElement.textContent);
Could we support placeholder text while the request is in progress? We could use the script contents as the placeholder, overwritten when the ajax request comes back. 

Something like this:

```
<marked-element>
  <div class="markdown-html"></div>
  <script type="text/markdown" src="../guidelines.md">
    Loading markdown...
  </script>
</marked-element>
```

2017-04-11 19:18 UTC, FredKSchott commented on marked-element.html
> +        }
Can we support the fail scenario as well? Something as simple as `this.markdown = 'text failed to load';` would add a lot of value.

2017-04-11 20:42 UTC, stramel commented on marked-element.html
> +      var markdownElement = Polymer.dom(this).querySelector('[type^="text/markdown"]');
It looks like `text/markdown` is the only thing registered for markdown in the IANA and RFC7763. Would you prefer to use `[type="text/markdown"]` here instead?

2017-04-11 20:42 UTC, stramel commented on demo/example.md
> +[![Build status](https://travis-ci.org/PolymerElements/marked-element.svg?branch=master)](https://travis-ci.org/PolymerElements/marked-element)
Yeah, was just being lazy 😅 I will find a different image to use, unless you have any suggestions.

2017-04-11 20:50 UTC, stramel commented on marked-element.html
> +      if (this.markdown) return;
Okay, would you like me to do this for some of the others that exist in here?

2017-04-11 22:11 UTC, stramel commented on marked-element.html
> +        this.markdown = this._unindent(markdownElement.textContent);
Good idea! Added 👍

2017-04-11 22:11 UTC, stramel commented on marked-element.html
> +       * network request.
Done

2017-04-11 22:11 UTC, stramel commented on marked-element.html
> +        }
Added a error event as well. Should we support both? I think maybe firing the event and allowing the consumer to do what they want with the content.

2017-04-11 22:11 UTC, stramel commented on README.md
> +via the `markdown` attribute
Attempted this, definitely open to suggestions

2017-04-11 22:11 UTC, stramel commented on demo/example.md
> +[![Build status](https://travis-ci.org/PolymerElements/marked-element.svg?branch=master)](https://travis-ci.org/PolymerElements/marked-element)
Used a polymer.svg harvested from `iron-image`

2017-04-11 22:15 UTC, stramel commented on demo/example.md
> +![Polymer](polymer.svg)
Could optionally just remove the image from the demo. The `polymer.svg` is 12.1kb

2017-04-11 22:15 UTC, stramel commented on marked-element.html
> +      if (markdownElement.src) {
Remote src will now just override the default content.

2017-04-14 13:44 UTC, stramel commented
@FredKSchott Updated based on comments

2017-04-18 04:12 UTC, stramel commented
@FredKSchott Friendly ping! Take a look at the fallback and error event. Thanks!

2017-04-19 01:22 UTC, stramel commented
@e111077 do you have any thoughts?

2017-04-19 02:16 UTC, e111077 requested changes

2017-04-19 02:16 UTC, e111077 commented on demo/example.md
> +![Polymer](polymer.svg)
Can you please? I don't think the svg is that necessary.

2017-04-19 02:16 UTC, e111077 commented
other than that LGTM

2017-04-19 02:24 UTC, stramel commented on demo/example.md
> +![Polymer](polymer.svg)
Sure thing!

2017-04-19 23:20 UTC, merged

2017-04-19 23:26 UTC, stramel commented
🎉 Thanks @e111077!

2017-05-02 21:37 UTC, FredKSchott commented
Thanks for 💪 on this @stramel!

2017-05-02 21:40 UTC, stramel commented
You're welcome! Glad to help out!